# Site settings
title: Panda Mints
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pandamints.com" # the base hostname & protocol for your site, e.g. http://example.com

# Home intro
intro-line-1: We are Panda Mints.
intro-line-2: We have passion for what we do and that passion leads us to create upscale fresh ideas for our clients.

# Contact button
button-label: Contact Us
button-link: hello@pandamints.com

# Projects
projects:
  
  - name: Ximena Calle
    description: Web design and development for a virtual classroom making possible for teacher to interact with students.
    image: ximenacalle.png
    link: http://ximenacalle.com

  - name: Jessica Iskander
    description: Web design and development for book author Jessica Iskander to showcase her work.
    image: jessica.png
    link: http://jessicaiskander.com

# Social
socialmedia:

  - name: Facebook
    link: https://www.facebook.com/pandamints

  - name: Twitter
    link: https://twitter.com/wearepandamints

  - name: Github
    link: https://github.com/pandamints

# Hotjar
hjid: 685213
hjsite: http://pandamints.com

# Google Analytics
gaid:
gasite: